"""empty message

Revision ID: 55e26a58626
Revises: 21208b3fbd9
Create Date: 2015-07-23 17:00:56.951049

"""

# revision identifiers, used by Alembic.
revision = '55e26a58626'
down_revision = '21208b3fbd9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_comment_association')
    op.add_column('comment', sa.Column('entity', sa.String(length=255), nullable=True))
    op.add_column('comment', sa.Column('entity_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'entity_id')
    op.drop_column('comment', 'entity')
    op.create_table('news_comment_association',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('news_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], name='news_comment_association_comment_id_fkey'),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], name='news_comment_association_news_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='news_comment_association_pkey')
    )
    ### end Alembic commands ###
