"""empty message

Revision ID: 541f6fdfc95
Revises: 1d33d23ddfc
Create Date: 2015-07-18 12:32:40.584700

"""

# revision identifiers, used by Alembic.
revision = '541f6fdfc95'
down_revision = '1d33d23ddfc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('skype', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'users', ['skype'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'skype')
    ### end Alembic commands ###
