"""empty message

Revision ID: 27ce1429e14
Revises: 33e6d962a7e
Create Date: 2015-07-30 16:33:31.303681

"""

# revision identifiers, used by Alembic.
revision = '27ce1429e14'
down_revision = '33e6d962a7e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_comment_association')
    op.drop_table('groups')
    op.drop_table('user_group_association')
    op.add_column('comment', sa.Column('entity', sa.String(length=255), nullable=True))
    op.add_column('comment', sa.Column('entity_id', sa.Integer(), nullable=True))
    op.add_column('news', sa.Column('views_count', sa.Integer(), nullable=True))
    op.drop_column('users', 'status')
    op.drop_column('users', 'roles')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('roles', postgresql.ARRAY(INTEGER()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('news', 'views_count')
    op.drop_column('comment', 'entity_id')
    op.drop_column('comment', 'entity')
    op.create_table('user_group_association',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='user_group_association_group_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_group_association_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_group_association_pkey')
    )
    op.create_table('groups',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='groups_pkey')
    )
    op.create_table('news_comment_association',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('news_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], name='news_comment_association_comment_id_fkey'),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], name='news_comment_association_news_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='news_comment_association_pkey')
    )
    ### end Alembic commands ###
