"""empty message

Revision ID: 538e19ebbde
Revises: None
Create Date: 2015-07-31 18:23:26.887297

"""

# revision identifiers, used by Alembic.
revision = '538e19ebbde'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=255), nullable=True),
    sa.Column('entity', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('extension', sa.String(length=255), nullable=True),
    sa.Column('hash', sa.String(length=255), nullable=True),
    sa.Column('external_link', sa.String(length=255), nullable=True),
    sa.Column('visible', sa.Boolean(create_constraint=False), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'department_id')
    op.drop_column('users', 'team_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('file')
    ### end Alembic commands ###
