"""empty message

Revision ID: 33e6d962a7e
Revises: 77145afe61
Create Date: 2015-07-27 20:04:49.315277

"""

# revision identifiers, used by Alembic.
revision = '33e6d962a7e'
down_revision = '3c64265776e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('roles', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('users', sa.Column('status', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    op.drop_column('users', 'roles')
    ### end Alembic commands ###
