"""changing_roles_and_users_model

Revision ID: 2ae9dfde557
Revises: None
Create Date: 2015-07-14 17:53:54.305510

"""

# revision identifiers, used by Alembic.
revision = '2ae9dfde557'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('photo', sa.String(), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'full_name')
    op.drop_column('roles', 'photo')
    ### end Alembic commands ###
