"""empty message

Revision ID: 21208b3fbd9
Revises: 3dd8a8208d2
Create Date: 2015-07-20 16:04:11.066323

"""

# revision identifiers, used by Alembic.
revision = '21208b3fbd9'
down_revision = '3dd8a8208d2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('likes_count', sa.Integer(), nullable=True))
    op.drop_column('news', 'comments_likes')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('comments_likes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('news', 'likes_count')
    ### end Alembic commands ###
