"""empty message

Revision ID: 4159a3ee034
Revises: 219066d79b6
Create Date: 2015-07-20 15:19:07.791877

"""

# revision identifiers, used by Alembic.
revision = '4159a3ee034'
down_revision = '219066d79b6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('photo_s', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photo_s')
    op.drop_column('users', 'photo')
    ### end Alembic commands ###
