"""empty message

Revision ID: 3c64265776e
Revises: 22355970659
Create Date: 2015-07-27 15:33:51.086492

"""

# revision identifiers, used by Alembic.
revision = '3c64265776e'
down_revision = '22355970659'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('views_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'views_count')
    ### end Alembic commands ###
