"""empty message

Revision ID: 36b07ca54f7
Revises: 21208b3fbd9
Create Date: 2015-07-22 16:51:18.868928

"""

# revision identifiers, used by Alembic.
revision = '36b07ca54f7'
down_revision = '21208b3fbd9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
