"""empty message

Revision ID: 219066d79b6
Revises: 541f6fdfc95
Create Date: 2015-07-20 14:41:25.255835

"""

# revision identifiers, used by Alembic.
revision = '219066d79b6'
down_revision = '541f6fdfc95'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
