Name="Candy's Skype Emotions Mod"
Author="Candy Chan"
Date="2007-01-18"
Version="1.0"
SelectionSize = 25, 25
WindowSize = 11, 8

Smiley = "01.gif"  , 0, ":) :-) :=)", ":)"
Smiley = "02.gif"  , 0, ":( :-( :=(", ":("
Smiley = "03.gif"  , 0, ":D :-D :=D :d :-d :=d", ":D"
Smiley = "04.gif"  , 0, "8) 8-) 8=) B) B-) B=)", "8)"
Smiley = "05.gif"  , 0, ":o :-o :=o :O :-O :=O", ":o"
Smiley = "06.gif"  , 0, ";) ;-) ;=)", ";)"
Smiley = "07.gif"  , 0, ";( ;-( ;=(", ";("
Smiley = "08.gif"  , 0, "(sweat) (:|", "(sweat)"
Smiley = "09.gif"  , 0, ":| :-| :=|", ":|"
Smiley = "10.gif" , 0, ":* :-* :=*", ":*"
Smiley = "11.gif" , 0, ":p :-p :=p :P :-P :=P", ":P"
Smiley = "12.gif" , 0, "(blush) :$ :-$ :=$ :">", "(blush)"
Smiley = "13.gif" , 0, ":^)", ":^)"
Smiley = "14.gif" , 1, "|-) I-) I=) (snooze)", "|-)"
Smiley = "15.gif" , 0, "|( |-( |=(", "|-("
Smiley = "16.gif" , 0, "(inlove)", "(inlove)"
Smiley = "17.gif" , 0, "]:) >:) (grin)", "]:)"
Smiley = "18.gif" , 0, "(talk)", "(talk)"
Smiley = "19.gif" , 0, "(yawn)", "(yawn)"
Smiley = "20.gif" , 0, "(puke) :& :-& :=&", "(puke)"
Smiley = "21.gif" , 0, "(doh)", "(doh)"
Smiley = "22.gif" , 18, ":@ :-@ :=@ x( x-( x=( X( X-( X=(", ":@"
Smiley = "23.gif" , 0, "(wasntme)", "(wasntme)"
Smiley = "24.gif" , 8, "(party)", "(party)"
Smiley = "25.gif" , 0, ":s :-s :=s :S :-S :=S", ":S"
Smiley = "26.gif" , 3, "(mm)", "(mm)"
Smiley = "27.gif" , 0, "8| 8-| 8=| B| B-| B=| (nerd)", "8-|"
Smiley = "28.gif" , 0, ":x :-x :=x :X :-X :=X :# :-# :=#"
Smiley = "29.gif" , 5, "(hi)", "(hi)"
Smiley = "30.gif" , 7, "(call)", "(call)"
Smiley = "31.gif" , 0, "(devil) (6)", (devil)"
Smiley = "32.gif" , 4, "(angel) (a) (A)", "(angel)"
Smiley = "33.gif" , 6, "(envy)", "(envy)"
Smiley = "34.gif" , 3, "(wait)", "(wait)"
Smiley = "35.gif" , 0, "(hug) (bear)", "(hug)"
Smiley = "36.gif" , 9, "(makeup) (kate)", "(makeup)"
Smiley = "37.gif" , 0, "(giggle) (chuckle)", "(chuckle)"
Smiley = "38.gif" , 0, "(clap)", "(clap)"
Smiley = "39.gif" , 0, "(think) :? :-? :=?", "(think)"
Smiley = "40.gif" , 7, "(bow)", "(bow)"
Smiley = "41.gif" , 0, "(rofl)", "(rofl)"
Smiley = "42.gif" , 0, "(whew)", "(whew)"
Smiley = "43.gif" , 0, "(happy)", "(happy)"
Smiley = "44.gif" , 0, "(smirk)", "(smirk)"
Smiley = "45.gif" , 0, "(nod)", "(nod)"
Smiley = "46.gif" , 0, "(shake)", "(shake)"
Smiley = "47.gif" , 0, "(punch)", "(punch)"
Smiley = "48.gif" , 0, "(emo)", "(emo)"
Smiley = "49.gif" , 6, "(y) (Y) (ok)", "(y)"
Smiley = "50.gif" , 12, "(n) (N)", "(n)"
Smiley = "51.gif" , 1, "(handshake)", "(handshake)"
Smiley = "52.gif" , 0, "(skype) (ss)", "(skype)"
Smiley = "53.gif" , 4, "(h) (H) (l) (L)", "(h)"
Smiley = "54.gif" , 7, "(u) (U)", "(u)"
Smiley = "55.gif" , 0, "(e) (m)", "(e)"
Smiley = "56.gif" , 21, "(F) (f)", "(F)"
Smiley = "57.gif" , 0, "(rain) (st) (london)", "(rain)"
Smiley = "58.gif" , 0, "(sun)", "(sun)"
Smiley = "59.gif" , 0, "(o) (O) (time)", "(o)"
Smiley = "60.gif" , 5, "(music)", "(music)"
Smiley = "61.gif" , 0, "(~) (film) (movie)", "(~)"
Smiley = "62.gif" , 0, "(mp) (ph)", "(mp)"
Smiley = "63.gif" , 0, "(coffee)", "(coffee)"
Smiley = "64.gif" , 0, "(pi) (pizza)", "(pi)"
Smiley = "65.gif" , 0, "(cash) (mo) ($)", "(cash)"
Smiley = "66.gif" , 0, "(flex) (muscle)", "(flex)"
Smiley = "67.gif" , 0, "(^) (cake)", "(^)"
Smiley = "68.gif" , 0, "(beer)", "(beer)"
Smiley = "69.gif" , 11, "(d) (D)", "(d)"
Smiley = "70.gif" , 4, "(dance) \o/ \:D/ \:d/", "(dance)"
Smiley = "71.gif" , 0, "(ninja)", "(ninja)"
Smiley = "72.gif" , 0, "(*)", "(*)"
Smiley = "bandit.gif" , 0, "(bandit)", "(bandit)"
Smiley = "drunk.gif" , 0, "(drunk)", "(drunk)"
Smiley = "finger.gif" , 0, "(finger)", "(finger)"
Smiley = "flagbg.gif" , 0, "(flag:bg)", "(flag:bg)"
Smiley = "headbang.gif" , 11, "(headbang) (banghead)", "(headbang)"
Smiley = "mooning.gif" , 5, "(mooning)", "(mooning)"
Smiley = "rock.gif" , 0, "(rock)", "(rock)"
Smiley = "smoke.gif" , 0, "(smoking) (smoke) (ci)", "(smoke)"
Smiley = "toivo.gif" , 0, "(toivo)", "(toivo)"
Smiley = "bug.gif" , 0, "(bug)", "(bug)"
Smiley = "fubar.gif" , 0, "(fubar)", "(fubar)"
Smiley = "poolparty.gif" , 0, "(poolparty)", "(poolparty)"
Smiley = "swear.gif" , , 0, "(swear)", "(swear)"
Smiley = "tmi.gif" , 0, "(tmi)", "(tmi)"
